# Generated by Django 2.2.9 on 2020-02-03 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=40)),
                ('postcode', models.CharField(max_length=7)),
                ('city', models.CharField(max_length=50)),
                ('street_address', models.CharField(max_length=60)),
                ('notes', models.TextField(blank=True)),
                ('date', models.DateField()),
                ('cancelled', models.DateField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Courses')),
                ('signup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='signups.Signup')),
            ],
        ),
    ]
