# Generated by Django 2.2.9 on 2020-02-05 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('signups', '0002_auto_20200205_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Courses'),
        ),
    ]
