# Generated by Django 2.2.9 on 2020-02-08 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signups', '0003_auto_20200205_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='rtgs_nr',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='signup',
            name='company_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='signup',
            name='full_name',
            field=models.CharField(max_length=100),
        ),
    ]
