# Generated by Django 2.2.9 on 2020-02-08 10:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signups', '0004_auto_20200208_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='cancelled',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='signup',
            name='date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
