# Generated by Django 2.2.9 on 2020-02-08 10:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signups', '0005_auto_20200208_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
