# Generated by Django 2.2.9 on 2020-02-08 11:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('signups', '0006_auto_20200208_1155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup',
            name='city',
        ),
        migrations.RemoveField(
            model_name='signup',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='signup',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='signup',
            name='postcode',
        ),
        migrations.RemoveField(
            model_name='signup',
            name='rtgs_nr',
        ),
        migrations.RemoveField(
            model_name='signup',
            name='street_address',
        ),
        migrations.AddField(
            model_name='signup',
            name='registrant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
