# Generated by Django 2.2.9 on 2020-02-09 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signups', '0007_auto_20200208_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
