# Generated by Django 2.2.10 on 2020-02-15 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signups', '0009_auto_20200209_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='payment_method',
            field=models.CharField(choices=[('CC', 'Credit card'), ('PIN', 'Pin'), ('IN', 'Invoice')], default='CC', max_length=100),
        ),
    ]
