# Generated by Django 2.2.10 on 2020-03-01 15:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('signups', '0010_signup_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signup', to='courses.Courses'),
        ),
        migrations.AlterField(
            model_name='signup',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='signup',
            name='registrant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
