# Generated by Django 2.2.9 on 2020-01-21 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('street_address', models.CharField(max_length=75)),
                ('postcode', models.CharField(max_length=6)),
                ('city', models.CharField(max_length=50)),
                ('tel', models.CharField(blank=True, max_length=20, null=True)),
                ('google_maps', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('ngt', models.BooleanField(default=False)),
                ('schrijftolk', models.BooleanField(default=False)),
                ('asl', models.BooleanField(default=False)),
                ('combitolk', models.BooleanField(default=False)),
                ('credit_language_and_interpreting_skills', models.FloatField()),
                ('credit_attitude', models.FloatField()),
                ('credit_target_audiences', models.FloatField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('ends', models.DateField()),
                ('endtime', models.TimeField()),
                ('costs', models.DecimalField(decimal_places=2, max_digits=7)),
                ('places', models.IntegerField(default=0)),
                ('description', models.TextField(null=True)),
                ('image', models.ImageField(default='img/logo_trainingshub.png', upload_to='course_pics')),
                ('course_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.Course_type')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Location')),
            ],
        ),
    ]
